### ISSUE TITLE
Harmonise referent test across functions?

### ISSUE THREAD

**Issue by anddis** [chstock/DTComPair#5]
Hello Christian,

Sorry for bothering you with another issue. I have been using `DTComPair` for some actual data analysis and I have noticed that:

- `sesp.rel` and `tpffpf.rel` both compute Test2/Test1: I coded them so to be consistent with `sesp.diff.ci`, `sesp.mcnemar`, and `sesp.exactbinom`'s behaviour (ie, Test2-Test1)
- `pv.rpv` computes Test1/Test2 
- `pv.gs` and `pv.wgs` compute abs(Test1-Test2) (as per R code), but the help file says Test2-Test1. Is there a reason for taking the absolute value?

I believe it would be good to harmonise the test used as referent across the package's functions. Let me know what you think.

(PS: one could consider also harmonising what is returned by the package's functions: either always a list of named vectors, like `sesp.diff.ci`, or a list of lists, like `sesp.mcnemar`.)

Thank you for considering this!

**Comment by chstock** [comment]
Hi Andrea, 

no worries, the input is absolutely appreciated. Consistency w.r.t. the reference is desirable indeed. I'd suggest Test 1 as the reference then. So it should be Test 2/ Test 1 or Test 2 - Test 1, respectively. 

Could you modify `pv.rpv` accordingly? I can look into `pv.gs` and `pv.wgs`. I vaguely recall the calculation of the confidence intervals was more convenient when considering the absolute values, but it should also be doable without `abs()`.

**Comment by chstock** [comment]
Regarding the returned objects: Also, good point. I think, I would prefer a structure like in `sesp.diff.ci` ( list of named vectors) over the structure in `sesp.mcnemar` (list of lists).

**Comment by anddis** [comment]
Hello Christian, 

- I edited the `pv.rpv` function so that Test 1 is used as the referent test (ie, Test2 / Test1) + the function returns a list of named vectors. I updated the help file accordingly,
- Made minor changes to`ellipse.pv.rpv` and to the example in the help file, 
- Fixed a couple of typos in `tpffpf.rel`'s and `sesp.rel`'s help file.

Any feedback is welcome.

**Comment by chstock** [comment]
Great - many thanks! Reviewed and now merged into main.
(My part still to do.)

**Comment by chstock** [comment]
`sesp.mcnemar` , `sesp.exactbinom`, `pv.gs` and `pv.wgs` now also return lists of vectors.

**Comment by chstock** [comment]
In `pv.gs`and `pv.wgs`, it is now `diff.ppv <- ppv.2-ppv.1` (instead of `diff.ppv <- abs(ppv.1-ppv.2)`), and accordingly for negative predictive values.

**Comment by anddis** [comment]
Brilliant! Thank you, Christian!

**Comment by chstock** [comment]
Changes are implemented
